server:
  port: 8082

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: savi-is
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.192.0.10:3306/savi-sys?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/savi-sys?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: miao123
#    username: savi_si
#    password: 123456

logging:
  level:
    com.savi.appauth: DEBUG