server:
  port: 8083

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-interval: 15s
        prefer-ip-address: true #使用IP地址进行注册
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
  redis:
    database: 0
    host: localhost
    port: 6379
    password: savi-is

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/savi-sys?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: miao123
#    url: jdbc:mysql://192.192.0.10:3306/savi-sys?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    username: savi_si
#    password: 123456

logging:
  level:
    com.savi.appauth: DEBUG